services:
  backend:
    build: backend
    environment:
      DATABASE_URL: postgres://local-dev:local@db/api?sslmode=disable
      API_SERVER_ADD: ":8000"
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - db
      - cache
    ports:
      - 8000:8000

  cache:
    image: redis:7.4.1-alpine
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning

  db:
    image: postgres:17.0-alpine
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: local-dev
      POSTGRES_PASSWORD: local
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate: &basemigrate
    profiles: ["tools"]
    image: migrate/migrate
    command: ["-path", "/tmp/migrations", "-database", "postgresql://local-dev:local@db/api?sslmode=disable", "up"]
    depends_on:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""

volumes:
  db-data:
  cache: